### ISSUE TITLE
KineticGeneratorModule

### ISSUE THREAD

**Issue by WESTMANT** [Andrew2448/Andrew2448PowersuitAddons#1]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 4/24/13 2:09 PM
Description: Ticking entity

java.lang.NoClassDefFoundError: net/machinemuse/api/MuseHeatUtils
    at andrew.powersuits.modules.KineticGeneratorModule.onPlayerTickActive(KineticGeneratorModule.java:61)
    at net.machinemuse.powersuits.tick.PlayerTickHandler.handle(PlayerTickHandler.java:70)
    at net.machinemuse.powersuits.tick.PlayerTickHandler.tickStart(PlayerTickHandler.java:44)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:122)
    at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:383)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:279)
    at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:45)
    at net.minecraft.world.World.func_72866_a(World.java:2336)
    at net.minecraft.world.World.func_72870_g(World.java:2298)
    at net.minecraft.world.World.func_72939_s(World.java:2144)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1852)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:834)
    at net.minecraft.client.Minecraft.run(Minecraft.java:759)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.machinemuse.api.MuseHeatUtils
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:238)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 15 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at andrew.powersuits.modules.KineticGeneratorModule.onPlayerTickActive(KineticGeneratorModule.java:61)
    at net.machinemuse.powersuits.tick.PlayerTickHandler.handle(PlayerTickHandler.java:70)
    at net.machinemuse.powersuits.tick.PlayerTickHandler.tickStart(PlayerTickHandler.java:44)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:28)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:122)
    at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:383)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:279)
    at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:45)
    at net.minecraft.world.World.func_72866_a(World.java:2336)
    at net.minecraft.world.World.func_72870_g(World.java:2298)

-- Entity being ticked --
Details:
    Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP)
    Entity ID: 332
    Entity Name: WESTMANT
    Entity's Exact location: -33.06, 76.62, 27.38
    Entity's Block location: World: (-34,76,27), Chunk: (at 14,4,11 in -3,1; contains blocks -48,0,16 to -33,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Entity's Momentum: -0.08, -0.08, -0.02
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2144)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['WESTMANT'/332, l='MpServer', x=-33.06, y=76.62, z=27.38]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-27,64,23), Chunk: (at 5,4,7 in -2,1; contains blocks -32,0,16 to -17,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 13766 game time, 13766 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 132 total; [EntityChicken['Chicken'/275, l='MpServer', x=39.59, y=65.00, z=-0.66], EntityChicken['Chicken'/274, l='MpServer', x=43.38, y=67.00, z=-0.44], EntityEnderman['Enderman'/273, l='MpServer', x=37.97, y=33.00, z=-32.28], EntityZombie['Zombie'/272, l='MpServer', x=37.88, y=33.00, z=-34.34], EntityChicken['Chicken'/277, l='MpServer', x=45.63, y=68.00, z=12.59], EntityChicken['Chicken'/281, l='MpServer', x=45.50, y=65.00, z=22.50], EntityChicken['Chicken'/280, l='MpServer', x=40.50, y=67.00, z=17.50], EntityBat['Bat'/287, l='MpServer', x=37.50, y=30.57, z=97.41], EntitySkeleton['Skeleton'/286, l='MpServer', x=36.50, y=26.00, z=82.50], EntitySheep['Sheep'/284, l='MpServer', x=36.50, y=66.00, z=79.50], EntityItem['item.item.egg'/258, l='MpServer', x=27.22, y=67.13, z=77.13], EntityItem['item.item.egg'/259, l='MpServer', x=25.66, y=67.13, z=78.13], EntityChicken['Chicken'/256, l='MpServer', x=28.50, y=67.00, z=77.50], EntityItem['item.item.egg'/257, l='MpServer', x=28.16, y=67.13, z=78.47], EntityChicken['Chicken'/262, l='MpServer', x=27.56, y=68.00, z=84.44], EntityPig['Pig'/260, l='MpServer', x=19.94, y=68.00, z=83.06], EntityPig['Pig'/261, l='MpServer', x=30.50, y=68.00, z=84.50], EntitySheep['Sheep'/288, l='MpServer', x=36.53, y=67.00, z=81.50], EntitySheep['Sheep'/289, l='MpServer', x=36.53, y=67.00, z=81.50], EntitySheep['Sheep'/290, l='MpServer', x=37.50, y=66.00, z=83.50], EntityPig['Pig'/291, l='MpServer', x=33.50, y=68.00, z=82.50], EntityPig['Pig'/292, l='MpServer', x=35.47, y=67.00, z=81.50], EntitySpider['Spider'/293, l='MpServer', x=41.50, y=12.00, z=103.25], EntityBat['Bat'/59, l='MpServer', x=-98.63, y=58.23, z=-8.72], EntityBat['Bat'/58, l='MpServer', x=-106.45, y=58.14, z=-14.75], EntityBat['Bat'/60, l='MpServer', x=-96.56, y=58.85, z=-10.28], EntityChicken['Chicken'/69, l='MpServer', x=-106.50, y=75.00, z=28.50], EntityChicken['Chicken'/70, l='MpServer', x=-106.50, y=75.00, z=28.50], EntityChicken['Chicken'/71, l='MpServer', x=-107.50, y=75.00, z=29.50], EntityChicken['Chicken'/72, l='MpServer', x=-103.50, y=74.00, z=27.50], EntityChicken['Chicken'/73, l='MpServer', x=-99.41, y=75.00, z=24.53], EntityChicken['Chicken'/74, l='MpServer', x=-99.50, y=73.00, z=25.50], EntityChicken['Chicken'/85, l='MpServer', x=-107.50, y=72.00, z=77.50], EntityChicken['Chicken'/84, l='MpServer', x=-104.50, y=72.00, z=78.50], EntityCreeper['Creeper'/80, l='MpServer', x=-104.50, y=63.00, z=40.50], EntityChicken['Chicken'/83, l='MpServer', x=-98.66, y=74.00, z=69.47], EntityChicken['Chicken'/82, l='MpServer', x=-106.50, y=74.00, z=70.50], EntityChicken['Chicken'/92, l='MpServer', x=-104.50, y=72.00, z=83.50], EntityClientPlayerMP['WESTMANT'/332, l='MpServer', x=-33.06, y=76.62, z=27.38], EntityChicken['Chicken'/91, l='MpServer', x=-104.50, y=72.00, z=81.50], EntityZombie['Zombie'/90, l='MpServer', x=-97.50, y=61.00, z=94.50], EntityBat['Bat'/103, l='MpServer', x=-80.25, y=53.92, z=-27.63], EntityBat['Bat'/101, l='MpServer', x=-86.16, y=30.23, z=-41.25], EntityItem['item.item.egg'/110, l='MpServer', x=-83.88, y=79.13, z=-19.88], EntityChicken['Chicken'/111, l='MpServer', x=-95.50, y=73.00, z=24.50], EntityItem['item.item.egg'/108, l='MpServer', x=-86.16, y=79.13, z=-17.34], EntityItem['item.item.egg'/109, l='MpServer', x=-87.09, y=79.13, z=-18.81], EntityChicken['Chicken'/106, l='MpServer', x=-85.50, y=79.00, z=-19.50], EntityChicken['Chicken'/107, l='MpServer', x=-83.34, y=79.00, z=-18.50], EntityChicken['Chicken'/104, l='MpServer', x=-88.44, y=79.00, z=-18.53], EntityChicken['Chicken'/105, l='MpServer', x=-85.22, y=79.00, z=-18.50], BlueSlime['Blue Slime'/834, l='MpServer', x=24.25, y=23.00, z=-35.44], EntityBat['Bat'/119, l='MpServer', x=-69.34, y=43.01, z=73.97], EntityBat['Bat'/118, l='MpServer', x=-90.09, y=46.57, z=88.47], EntityItem['item.item.egg'/117, l='MpServer', x=-87.75, y=75.13, z=29.56], EntityItem['item.item.egg'/116, l='MpServer', x=-91.38, y=72.13, z=20.94], EntityChicken['Chicken'/114, l='MpServer', x=-96.41, y=75.00, z=23.56], EntityChicken['Chicken'/113, l='MpServer', x=-86.50, y=75.00, z=29.50], EntityChicken['Chicken'/112, l='MpServer', x=-82.56, y=80.00, z=32.47], EntityBat['Bat'/137, l='MpServer', x=-67.06, y=34.98, z=-15.91], EntityItem['item.item.egg'/139, l='MpServer', x=-75.13, y=77.13, z=26.66], EntitySkeleton['Skeleton'/138, l='MpServer', x=-76.91, y=50.00, z=19.50], NitroCreeper['Nitro Creeper'/141, l='MpServer', x=-67.50, y=60.00, z=91.50], EntityChicken['Chicken'/140, l='MpServer', x=-71.81, y=76.00, z=30.53], EntitySkeleton['Skeleton'/143, l='MpServer', x=-67.88, y=11.00, z=99.53], EntityZombie['Zombie'/142, l='MpServer', x=-70.50, y=13.00, z=103.50], EntityItem['item.tile.sapling.oak'/158, l='MpServer', x=-51.84, y=84.13, z=-19.13], NitroCreeper['Nitro Creeper'/159, l='MpServer', x=-48.50, y=26.00, z=16.50], EntityEnderman['Enderman'/144, l='MpServer', x=-100.09, y=12.00, z=76.06], EntityChicken['Chicken'/171, l='MpServer', x=-38.50, y=80.00, z=-52.50], EntityChicken['Chicken'/170, l='MpServer', x=-39.50, y=81.00, z=-52.50], EntitySkeleton['Skeleton'/175, l='MpServer', x=-34.44, y=72.00, z=-1.06], EntityChicken['Chicken'/172, l='MpServer', x=-38.50, y=80.00, z=-50.50], NitroCreeper['Nitro Creeper'/163, l='MpServer', x=-61.06, y=25.00, z=88.50], EntityZombie['Zombie'/162, l='MpServer', x=-62.31, y=40.07, z=85.53], EntityBat['Bat'/161, l='MpServer', x=-57.31, y=17.82, z=77.53], EntityEnderman['Enderman'/160, l='MpServer', x=-63.59, y=17.00, z=78.66], EntityCreeper['Creeper'/164, l='MpServer', x=-51.56, y=57.00, z=78.00], EntityEnderman['Enderman'/184, l='MpServer', x=-38.88, y=45.00, z=82.50], EntityBat['Bat'/178, l='MpServer', x=-28.47, y=49.00, z=46.91], NitroCreeper['Nitro Creeper'/179, l='MpServer', x=-37.50, y=29.00, z=76.50], EntitySpider['Spider'/176, l='MpServer', x=-48.00, y=25.01, z=13.30], EntityCreeper['Creeper'/177, l='MpServer', x=-46.50, y=55.00, z=4.50], EntityBat['Bat'/182, l='MpServer', x=-45.53, y=20.92, z=75.44], EntityBat['Bat'/183, l='MpServer', x=-37.44, y=25.11, z=77.63], EntitySkeleton['Skeleton'/180, l='MpServer', x=-41.88, y=65.00, z=75.56], EntityCreeper['Creeper'/181, l='MpServer', x=-47.50, y=64.00, z=70.50], NitroCreeper['Nitro Creeper'/205, l='MpServer', x=-30.50, y=29.00, z=54.50], EntityCreeper['Creeper'/204, l='MpServer', x=-28.50, y=26.00, z=52.50], EntitySlime['Slime'/207, l='MpServer', x=-24.31, y=29.02, z=65.69], EntityCreeper['Creeper'/206, l='MpServer', x=-30.50, y=29.00, z=57.50], EntitySkeleton['Skeleton'/201, l='MpServer', x=-30.13, y=34.00, z=9.47], EntityZombie['Zombie'/200, l='MpServer', x=-20.50, y=44.00, z=10.50], EntityCreeper['Creeper'/203, l='MpServer', x=-19.91, y=52.00, z=43.75], EntityItem['item.tile.sapling.birch'/202, l='MpServer', x=-31.47, y=74.13, z=31.88], NitroCreeper['Nitro Creeper'/197, l='MpServer', x=-21.50, y=31.00, z=1.50], EntitySkeleton['Skeleton'/196, l='MpServer', x=-24.47, y=71.00, z=-8.06], EntityCreeper['Creeper'/199, l='MpServer', x=-31.03, y=27.00, z=9.38], EntityCreeper['Creeper'/198, l='MpServer', x=-30.50, y=30.00, z=0.50], EntitySkeleton['Skeleton'/195, l='MpServer', x=-26.50, y=31.00, z=-1.50], EntityOcelot['Ocelot'/194, l='MpServer', x=-21.78, y=83.00, z=-28.84], EntityChicken['Chicken'/214, l='MpServer', x=-29.56, y=70.00, z=104.53], NitroCreeper['Nitro Creeper'/208, l='MpServer', x=-24.50, y=19.00, z=83.50], EntityBat['Bat'/209, l='MpServer', x=-28.91, y=17.29, z=88.88], EntityZombie['Zombie'/210, l='MpServer', x=-20.50, y=18.00, z=105.50], EntityCreeper['Creeper'/211, l='MpServer', x=-16.50, y=29.00, z=99.50], EntitySheep['Sheep'/239, l='MpServer', x=15.16, y=64.00, z=-42.88], EntitySkeleton['Skeleton'/236, l='MpServer', x=-13.47, y=22.37, z=105.31], EntityCreeper['Creeper'/235, l='MpServer', x=-15.50, y=29.00, z=99.50], EntityItem['item.item.egg'/232, l='MpServer', x=-1.19, y=71.13, z=62.88], EntityChicken['Chicken'/231, l='MpServer', x=-1.50, y=70.00, z=62.50], EntityBat['Bat'/230, l='MpServer', x=-4.31, y=32.02, z=26.69], EntityBat['Bat'/229, l='MpServer', x=-14.25, y=31.10, z=10.78], EntitySkeleton['Skeleton'/228, l='MpServer', x=-4.50, y=65.00, z=-9.50], BlueSlime['Blue Slime'/227, l='MpServer', x=-15.38, y=29.00, z=-4.63], EntitySkeleton['Skeleton'/226, l='MpServer', x=-13.53, y=68.00, z=-41.59], EntitySkeleton['Skeleton'/225, l='MpServer', x=-7.31, y=27.03, z=-44.69], EntityChicken['Chicken'/254, l='MpServer', x=27.50, y=67.00, z=78.50], EntityChicken['Chicken'/255, l='MpServer', x=29.50, y=67.00, z=78.50], EntityBat['Bat'/252, l='MpServer', x=28.50, y=33.76, z=-7.56], EntityBat['Bat'/253, l='MpServer', x=11.28, y=24.00, z=1.09], NitroCreeper['Nitro Creeper'/251, l='MpServer', x=29.50, y=34.00, z=-14.50], EntitySkeleton['Skeleton'/248, l='MpServer', x=11.56, y=20.00, z=106.94], EntitySkeleton['Skeleton'/249, l='MpServer', x=9.31, y=21.00, z=103.94], EntityItem['item.item.egg'/246, l='MpServer', x=2.72, y=68.13, z=58.13], EntityItem['item.item.egg'/247, l='MpServer', x=0.16, y=69.13, z=62.88], EntityChicken['Chicken'/244, l='MpServer', x=0.31, y=70.00, z=63.75], EntityChicken['Chicken'/245, l='MpServer', x=2.50, y=69.00, z=62.50], EntitySheep['Sheep'/242, l='MpServer', x=-0.66, y=66.00, z=-24.53], EntityChicken['Chicken'/243, l='MpServer', x=3.50, y=68.00, z=59.50], EntitySheep['Sheep'/240, l='MpServer', x=3.66, y=72.00, z=-20.34], EntitySheep['Sheep'/241, l='MpServer', x=3.53, y=68.00, z=-21.47]]
    Retry entities: 0 total; []
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:441)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2413)
    at net.minecraft.client.Minecraft.run(Minecraft.java:775)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.5.1
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_21, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1393651496 bytes (1329 MB) / 2405040128 bytes (2293 MB) up to 4772200448 bytes (4551 MB)
    JVM Flags: 2 total; -Xms1024m -Xmx5120m
    AABB Pool Size: 17044 (954464 bytes; 0 MB) allocated, 2 (112 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 71
    FML: MCP v7.44 FML v5.1.36.666 Minecraft Forge 7.7.1.666 40 mods loaded, 40 mods active
    mcp{7.44} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{5.1.36.666} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{7.7.1.666} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{0.8.6.1} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.5.1.0} [CoFH Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.5.2.9} [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowerCrystalsCore{1.1.2} [PowerCrystals Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHNetwork{1.5.1.0} [CoFHNetwork](CoFHCore-1.5.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHWorld{1.5.1.0} [CoFHWorld](CoFHCore-1.5.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{3.5.0} [BuildCraft](buildcraft-A-3.5.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{3.5.0} [BC Transport](buildcraft-A-3.5.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{3.5.0} [BC Silicon](buildcraft-A-3.5.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{2.3.1.0} [Thermal Expansion](ThermalExpansion-2.3.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{1.115.295-lf} [IndustrialCraft 2](industrialcraft-2_1.115.295-lf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics{rv.10.g} [Applied Energistics](appeng-rv10-g.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.1.6} [BiblioCraft](BiblioCraft[v1.1.6].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{3.5.0} [BC Builders](buildcraft-A-3.5.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{3.5.0} [BC Energy](buildcraft-A-3.5.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{3.5.0} [BC Factory](buildcraft-A-3.5.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChickenChunks{1.3.2.5} [ChickenChunks](ChickenChunks 1.3.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft{1.52} [ComputerCraft](ComputerCraft1.52.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CCTurtle{1.52} [ComputerCraft Turtles](ComputerCraft1.52.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage{1.4.2.4} [EnderStorage](EnderStorage 1.4.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FlatBedrock{1.5.1R1.1.1} [FlatBedrock](FlatBedrock-1.1.1-32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{2.1.2.28} [Forestry for Minecraft](forestry-A-2.1.2.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{1.17.1} [The Twilight Forest](twilightforest-1.17.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GregTech_Addon{MC151_V3.02} [GregTech-Addon](gregtechmod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{1.0.0} [iChunUtil](iChunUtil1.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.53} [Inventory Tweaks](InventoryTweaks-1.53.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{5.2.4.379} [Iron Chest](ironchest-universal-1.5.1-5.2.4.379.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GraviSuite{1.9} [Gravitation Suite](mod_zGraviSuite_1_9.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mmmPowersuits{0.4.2-314} [MachineMuse's Modular Powersuits](ModularPowersuits-0.4.2-326.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PowersuitAddons{0.2.2-76} [Andrew2448's Modular Powersuits Addon](MPSA-0.2.2-76_MPS-326.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mystcraft{0.10.3.00} [Mystcraft](mystcraft-uni-1.5.1-0.10.3.00.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura{1.5.1_2.0.18} [Natura](Natura_1.5.1_2.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIPlugins{1.0.6.2} [NEI Plugins](NEIPlugins-1.0.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PortalGun{1.5.1} [PortalGun](PortalGun1.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    StevesCarts{2.0.0.a100} [Steve's Carts](StevesCarts2.0.0.a100.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.5.1_1.3dev.20} [Tinkers' Construct](TConstruct_1.5.1_1.3dev.20.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    mod_ZanMinimap{0.9.4} [mod_ZanMinimap](ZansMinimap1.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LWJGL: 2.4.2
    OpenGL: GeForce GTX 650/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Texture Pack: Default
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 586 (32816 bytes; 0 MB) allocated, 11 (616 bytes; 0 MB) used

**Comment by Andrew2448** [comment]
Update your ModularPowersuits version to atleast version 342. You will have better luck with the more recent versions though (~380s)
