### ISSUE TITLE
Leaf Blower bug found.

### ISSUE THREAD

**Issue by Amperthorpe** [Andrew2448/Andrew2448PowersuitAddons#10]
I found out what the problem was. I made a video: http://www.youtube.com/watch?v=eXq_d8KbwLQ

**Comment by Andrew2448** [comment]
In 131 I made that module a right clicker instead of a block breaker, can you try with that and see if it fixed it by coincidence?

**Comment by Amperthorpe** [comment]
Sure. I'll do that right now.

**Comment by Amperthorpe** [comment]
Do you have a download for it? The latest from machinemuse.net says 132 but it's still a normal break for me.

**Comment by Andrew2448** [comment]
http://build.technicpack.net/job/ModularPowersuitsAddons/131/ Try removing the module and reinstalling, it might be a little weird at first because of the switch.

**Comment by Amperthorpe** [comment]
I used that build, made a new world, and it's definitely not a right click module. The axe isn't even working at all, and the leaves are still bugging.

edit: opps, forgot to give it power. The axe works.

**Comment by Andrew2448** [comment]
Cannot replicate, people are telling me it's definitely working as a right clicker.
