### ISSUE TITLE
Leaf Blower Item Drops

### ISSUE THREAD

**Issue by Saklad5** [Andrew2448/Andrew2448PowersuitAddons#14]
The leaf blower module appears to drop only the block you are pointing at, instead of each individual item that was destroyed. For example, if you highlight a flower surrounded by 8 tall grass and use the leaf blower, 9 flowers will drop, instead of 1 flower and 8 grass/seeds. it even drops blocks under the affected items if you highlight the block instead, despite the blocks not being touched. This can get quite annoying, so please fix it soon.

**Comment by Andrew2448** [comment]
Yeah I'm aware of this one, unfortunately haven't found a fix yet. A workaround is to right click the actual grass, as this only happens if you right click a block on the ground.

**Comment by NewcastleGeek** [comment]
I actually think this is game breaking especially on a server :/ Might be an idea to disable it in the next update till a fix is found

**Comment by Andrew2448** [comment]
You can disable any module in the configs.

**Comment by AKA-Syenite** [comment]
Fixed by #15
