### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ikyonawooka** [Andrew2448/Andrew2448PowersuitAddons#20]
If i run your mod in single player it works fine. But when i add it to my server it crashes. If i remove your addon from my server it works. 

log from crash-report
http://pastebin.com/6fdHr78k

log from forgemodloader-server
http://pastebin.com/sQSPNM8b

**Comment by Andrew2448** [comment]
This is an IC2 problem that may take a while to fix because I don't know the exact source. For now, backdating your IC2 should fix it.

**Comment by Andrew2448** [comment]
Actually now that I go over my code there is nothing I do that could cause this. Try bringing this to the IC guys.
