### ISSUE TITLE
Lightning Summoner sets air on fire

### ISSUE THREAD

**Issue by ShinobiDragoon** [Andrew2448/Andrew2448PowersuitAddons#21]
Forge build 712, MPS build 534, MPSA build 150, Forestry 2.2.6.3, Railcraft 7.2.2.0, IC2 build 348.

Upon using the Lightning Summoner module, a 3x3 area, 2 blocks high, surrounding or in close proximity to the user is ignited, regardless of where the lightning bolt is summoned. The ignited blocks are at ground level and 1 block higher, and if the player is standing on level terrain, that means that fires are being started on the air blocks at foot level. However, as the fire visual is not rendered unless attached to a solid block, the fires are invisible (it is, however, still audible). Replacing the affected air blocks with solid blocks will render the fire visible and can then be extinguished. Standing inside the affected air blocks results in the standard "on fire" player visual in first person mode, but the player takes no fire damage and the equipped suit does not generate heat. Tested with a heat sink to ensure it is not the result of the suit overheating. No modules other than the Summoner, a single battery module and single heat sink were installed.

Edit: realised I hadn't updated my Forge build for a while, retested with Forge build 737 with the same result.

**Comment by Andrew2448** [comment]
Hrm...fire spawning around the player was intended to be a feature but I may have derped it up. I'll just remove it for now and revisit it later.
