### ISSUE TITLE
Request: Slider for water tank: Cooling Threshhold

### ISSUE THREAD

**Issue by DoomRater** [Andrew2448/Andrew2448PowersuitAddons#24]
How about a configurable slider to determine at what percentage the water tank starts dumping water into the system?  That way those of us who want to keep our heat levels at zero can do so while others can try to stabilize the heat at whatever percentage of maximum heat they find most efficient, say some players like it kept around 75% or 50%.

**Comment by Andrew2448** [comment]
I like this idea. I'll do this. :)

**Comment by Andrew2448** [comment]
Sorry it took so long but I finally did it.

**Comment by DoomRater** [comment]
Reminding me of me when I get requests for a project I'm working on.  No prob, can't wait to test it all out!
