### ISSUE TITLE
MPSA Magnet module bug

### ISSUE THREAD

**Issue by DrunkenWolfer** [Andrew2448/Andrew2448PowersuitAddons#3]
When the magnet tries to pick up an item the server has an internal error and kicks me.
The server still runing but I can't connect because the item stil there and I keep getting kicked.

Using ModularPowersuits-0.6.0-421 and MPSA-0.2.2-83+_MPS-386

Server console error: http://pastebin.com/yQbGiRhh

**Comment by Andrew2448** [comment]
Fixed in 86.
